BEGIN;

-- public.profiles pertenece al rol postgres. No se cambia ownership ni se eleva
-- app_user: los campos de identidad operativa viven en una extension local.
CREATE TABLE IF NOT EXISTS public.auth_profiles_local (
  auth_user_id uuid PRIMARY KEY,
  email text,
  username text,
  assignment_code text,
  legacy_user_id bigint,
  last_login_at timestamptz,
  source_system text,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS auth_profiles_local_email_unique_idx
  ON public.auth_profiles_local (lower(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS auth_profiles_local_username_unique_idx
  ON public.auth_profiles_local (lower(username)) WHERE username IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS auth_profiles_local_legacy_user_id_unique_idx
  ON public.auth_profiles_local (legacy_user_id) WHERE legacy_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.derivation_recipient_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_key text NOT NULL,
  recipient_label text NOT NULL,
  email text NOT NULL,
  delivery_type text NOT NULL CHECK (delivery_type IN ('to', 'cc')),
  display_name text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  notify_on_completion boolean NOT NULL DEFAULT false,
  visible_in_mobile boolean NOT NULL DEFAULT true,
  UNIQUE (recipient_key, email)
);
CREATE INDEX IF NOT EXISTS derivation_recipient_contacts_active_idx
  ON public.derivation_recipient_contacts (recipient_key, is_active, sort_order, id);

CREATE TABLE IF NOT EXISTS public.profile_manual_signatures (
  profile_id uuid PRIMARY KEY,
  storage_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profile_signature_certificates (
  profile_id uuid PRIMARY KEY,
  storage_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  cert_issuer text NOT NULL,
  cert_subject text NOT NULL,
  cert_valid_to timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.push_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  expo_push_token text NOT NULL,
  device_platform text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (profile_id, expo_push_token)
);
CREATE INDEX IF NOT EXISTS idx_push_tokens_profile_id ON public.push_tokens (profile_id);

CREATE TABLE IF NOT EXISTS public.push_notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL DEFAULT 'supervision_created',
  supervision_id bigint,
  assigned_user_id integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_push_outbox_unprocessed
  ON public.push_notification_outbox (created_at) WHERE processed_at IS NULL;

CREATE TABLE IF NOT EXISTS public.supervision_signatures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supervision_id bigint NOT NULL,
  signer_role text NOT NULL CHECK (signer_role IN ('cliente', 'inspector', 'supervision')),
  signature_kind text NOT NULL CHECK (signature_kind IN ('grafica', 'digital')),
  signer_name text,
  cert_subject text,
  cert_issuer text,
  cert_valid_to timestamptz,
  storage_path text NOT NULL,
  signed_at timestamptz NOT NULL DEFAULT now(),
  signed_by_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_supervision_signatures_supervision_id
  ON public.supervision_signatures (supervision_id, signed_at DESC);
CREATE INDEX IF NOT EXISTS idx_supervision_signatures_latest_by_role
  ON public.supervision_signatures (supervision_id, signer_role, signed_at DESC);

CREATE TABLE IF NOT EXISTS public.private_file_objects (
  bucket text NOT NULL,
  object_path text NOT NULL,
  local_relative_path text NOT NULL,
  content_type text,
  size_bytes bigint NOT NULL,
  sha256 text NOT NULL,
  source_updated_at timestamptz,
  migrated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (bucket, object_path),
  UNIQUE (local_relative_path)
);

CREATE TABLE IF NOT EXISTS public.supabase_boundary_migrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_key text NOT NULL UNIQUE,
  report jsonb NOT NULL,
  completed_at timestamptz NOT NULL DEFAULT now()
);

COMMIT;
